# Autogenerated by LiteX / git: a4cc859d
quartus_map --read_settings_files=on  --write_settings_files=off de2_s003_switches -c de2_s003_switches
quartus_fit --read_settings_files=off --write_settings_files=off de2_s003_switches -c de2_s003_switches
quartus_asm --read_settings_files=off --write_settings_files=off de2_s003_switches -c de2_s003_switches
quartus_sta de2_s003_switches -c de2_s003_switches
if [ -f "de2_s003_switches.sof" ]
then
    quartus_cpf -c de2_s003_switches.sof de2_s003_switches.rbf
fi
