set_property SRC_FILE_INFO {cfile:/home/lam/data2/edabk/fpga_101/lab001/solutions/build_s005_rgbblink/s005_rgbblink.xdc rfile:../s005_rgbblink.xdc id:1 order:EARLY} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB8 [get_ports {user_led0}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA8 [get_ports {user_led1}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC9 [get_ports {user_led2}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC K28 [get_ports {clk156_p}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC K29 [get_ports {clk156_n}]
