# Autogenerated by LiteX / git: a977adf5
set -e -u -x -o pipefail
quartus_map --read_settings_files=on  --write_settings_files=off de2_s002_blink -c de2_s002_blink
quartus_fit --read_settings_files=off --write_settings_files=off de2_s002_blink -c de2_s002_blink
quartus_asm --read_settings_files=off --write_settings_files=off de2_s002_blink -c de2_s002_blink
quartus_sta de2_s002_blink -c de2_s002_blink
if [ -f "de2_s002_blink.sof" ]
then
    quartus_cpf -c de2_s002_blink.sof de2_s002_blink.rbf
fi
