// -----------------------------------------------------------------------------
// Auto-Generated by:        __   _ __      _  __
//                          / /  (_) /____ | |/_/
//                         / /__/ / __/ -_)>  <
//                        /____/_/\__/\__/_/|_|
//                     Build your hardware, easily!
//                   https://github.com/enjoy-digital/litex
//
// Filename   : s004_switches.v
// Device     : xc7k325t-ffg900-2
// LiteX sha1 : a4cc859d
// Date       : 2022-05-17 00:07:26
//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
// Module
//------------------------------------------------------------------------------

module s004_switches (
	output wire user_led1,
	input  wire user_btn1,
	output wire user_led2,
	input  wire user_btn2,
	output wire user_led3,
	input  wire user_btn3,
	output wire user_led4,
	input  wire user_btn4,
	output wire user_led0,
	input  wire user_btn0,
	(* dont_touch = "true" *)	input  wire clk156_p,
	input  wire clk156_n
);


//------------------------------------------------------------------------------
// Signals
//------------------------------------------------------------------------------

wire sys_clk;
wire sys_rst;
wire por_clk;
wire clk_se;
reg  int_rst = 1'd1;

//------------------------------------------------------------------------------
// Combinatorial Logic
//------------------------------------------------------------------------------

assign user_led1 = user_btn1;
assign user_led2 = user_btn2;
assign user_led3 = user_btn3;
assign user_led4 = user_btn4;
assign user_led0 = (~user_btn0);
assign sys_clk = clk_se;
assign por_clk = clk_se;
assign sys_rst = int_rst;


//------------------------------------------------------------------------------
// Synchronous Logic
//------------------------------------------------------------------------------

always @(posedge por_clk) begin
	int_rst <= 1'd0;
end

always @(posedge sys_clk) begin
	if (sys_rst) begin
	end
end


//------------------------------------------------------------------------------
// Specialized Logic
//------------------------------------------------------------------------------

IBUFDS IBUFDS(
	.I(clk156_p),
	.IB(clk156_n),
	.O(clk_se)
);

endmodule

// -----------------------------------------------------------------------------
//  Auto-Generated by LiteX on 2022-05-17 00:07:26.
//------------------------------------------------------------------------------
