# Autogenerated by LiteX / git: a4cc859d
quartus_map --read_settings_files=on  --write_settings_files=off de2_s005_rgbblink -c de2_s005_rgbblink
quartus_fit --read_settings_files=off --write_settings_files=off de2_s005_rgbblink -c de2_s005_rgbblink
quartus_asm --read_settings_files=off --write_settings_files=off de2_s005_rgbblink -c de2_s005_rgbblink
quartus_sta de2_s005_rgbblink -c de2_s005_rgbblink
if [ -f "de2_s005_rgbblink.sof" ]
then
    quartus_cpf -c de2_s005_rgbblink.sof de2_s005_rgbblink.rbf
fi
